### PR TITLE
Feature : Added a new way to share the data across different platforms.

### PR DESCRIPTION
**Pull request by Mohitsen11**
# What is the feature you added ?
Added a new share icon in UI which expands the sharing feature by clicking on it.

# what changes you made ?
Changes html , css and js for new way of sharing...work is still running.

# Why you created PR ?
So that you can see the work and give me the feedback about what to change , what to add more and so on.

Facebook and instagram sharing is pending.
Twitter logo has to be changed..
Sharing popup animation needs to be change.

### CODE REVIEW

**Comment by actuallyaryaman** [comment]
good job! @Mohitsen11 
- i would point out that the transition looks off so if you would look into it and make it a simple slide up and slide down sort entrance and exit animation..
- i suggest you remove the facebook icon from the options altogether because we ain't that big of a fan.
thanks for your contributions!🌟🌟

**Comment by Mohitsen11** [comment]
I have changed the transition of popup sharing box and removed the facebook icon and updated the new twitter logo.

One more thing is for shaing data on insta Fuelish has to register on meta developer account as an app so i was not able to do that so replaced insta with reddit platform.

And please add the lable of hactoberfest!!

Happy to code!!
Happy to contribute!!

**Comment by actuallyaryaman** [comment]
In the below screenshots there's a noticeable difference in the alignment and spacing of contents.
Kindly look into it so I can merge your pr.

- Your Preview:
Screenshot_20231021_091930_Brave

- Current Deployment:
Screenshot_20231021_091919_Brave

**Comment by Mohitsen11** [comment]
Work is done!!

Happy to contribute!!
Happy to code!!

**Comment by Asvin1** [comment]
Great work, the menu looks good!

**Comment by Mohitsen11** [comment]
> Great work, the menu looks good!

Thank you! I'm happy you liked it.

**Pull request merged**
