### PR TITLE
Feature : Added a whatsapp sharing button in the UI.

### PR DESCRIPTION
**Pull request by Mohitsen11**
# What is the feature you added ?
Added a WhatsApp sharing button in the UI so that fuel data can be shared.

# Why this feature is needed to Fuelish?
Almost every person uses Whatsapp in their day to day life and it is a very common medium to share info. So adding this feature makes easy to share the fuel Data.

# What data is being sent/shared on WhatsApp?
There is a one line intro note with the website link and then addressing the city and state then fuel prices and changes.

Want to contribute more in this project!!

### CODE REVIEW

**Comment by Mohitsen11** [comment]
And please give me the label of hactoberfest !!!

**Comment by Asvin1** [comment]
Replace the button with a whatsapp icon and make it visible in the initial state

**Comment by Mohitsen11** [comment]
> Replace the button with a whatsapp icon and make it visible in the initial state

Replaced the button with a whatsapp icon and made it visible.
Work done!!

**Comment by actuallyaryaman** [comment]
@Mohitsen11 kindly remove the text field, the icon is sufficient enough.
also remove the button from intitial state because it is useless just being put up their without any function.(@Asvin1 )
rest all works fine and can be merged after the mentioned changes.
thanks

**Comment by Mohitsen11** [comment]
> @Mohitsen11 kindly remove the text field, the icon is sufficient enough. also remove the button from intitial state because it is useless just being put up their without any function.(@Asvin1 ) rest all works fine and can be merged after the mentioned changes. thanks

Removed the text field and button from initial state.
Work done!!

**Review by actuallyaryaman — APPROVED** [review]

**Comment by actuallyaryaman** [comment]
@Mohitsen11 if you can, I'd like you to look into a solution so that sharing is not limited to WhatsApp only.

**Comment by Mohitsen11** [comment]
> @Mohitsen11 if you can, I'd like you to look into a solution so that sharing is not limited to WhatsApp only.

Okay..lets do it!

**Pull request merged**
