### PR TITLE
 Add a site-visit counter #20 

### PR DESCRIPTION
**Pull request by krishprav**
Added Feature :site-visit counter #20

### CODE REVIEW

**Comment by Asvin1** [comment]
@krishprav you are storing the visit count in local storage which won't reflect for all users that visit the site

**Comment by krishprav** [comment]
Yes thank you for pointing.I will update.

**Comment by actuallyaryaman** [comment]
@krishprav I checked your deployment and it seems the site counter is not being updated at all.

**Comment by actuallyaryaman** [comment]
closing this pr as already completed.

**Pull request closed without merging**
